# Generated by Django 4.0.2 on 2022-03-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='start_end',
            field=models.BooleanField(default='True'),
        ),
    ]
