# Generated by Django 4.0.2 on 2022-03-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_start_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='start_end',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
