# Generated by Django 4.0.2 on 2022-03-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_employee_start_end_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='transportation_expenses',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
