# Generated by Django 4.0.2 on 2022-03-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_rename_time_work_employee_time_work_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='time_work_day',
            new_name='time_rest_day',
        ),
        migrations.AddField(
            model_name='employee',
            name='time_restraint_day',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
