# Generated by Django 4.0.2 on 2022-03-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_time_work_day_employee_time_rest_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sum_pay',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_wage',
            field=models.CharField(default='時給を入力してください', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='transportation_expenses',
            field=models.CharField(default='交通費を入力してください', max_length=100),
        ),
    ]
