# Generated by Django 4.0.2 on 2022-03-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_employee_sum_pay_alter_employee_hourly_wage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sum_pay',
            new_name='rest_count',
        ),
    ]
