# Generated by Django 4.0.2 on 2022-03-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_rename_sum_pay_employee_rest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sum_pay',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_rest_day',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
