# Generated by Django 4.0.2 on 2022-03-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_employee_sum_pay_alter_employee_time_rest_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='rest_count',
            new_name='actual_working_hour',
        ),
    ]
