# Generated by Django 4.0.2 on 2022-03-07 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_rename_rest_count_employee_actual_working_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transportation_expenses', models.CharField(default=0, max_length=100)),
                ('hourly_wage', models.CharField(default=0, max_length=100)),
                ('actual_working_hour', models.CharField(default=0, max_length=100)),
                ('sum_pay', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_wage',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='transportation_expenses',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
