# Generated by Django 4.0.2 on 2022-03-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_basic_inf_actual_working_hour_basic_inf_hourly_wage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='actual_working_hour',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hourly_wage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sum_pay',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='transportation_expenses',
        ),
        migrations.AlterField(
            model_name='basic_inf',
            name='hourly_wage',
            field=models.CharField(default=1000, max_length=100),
        ),
    ]
