# Generated by Django 4.0.2 on 2022-03-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_basic_inf_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_inf',
            name='test',
        ),
    ]
